//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewellClark.Wpf.UserControls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewellClark.Wpf.UserControls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex Options.
        /// </summary>
        public static string regexOptions {
            get {
                return ResourceManager.GetString("regexOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiled.
        /// </summary>
        public static string regexOptions_compiled {
            get {
                return ResourceManager.GetString("regexOptions_compiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture invariant.
        /// </summary>
        public static string regexOptions_cultureInvariant {
            get {
                return ResourceManager.GetString("regexOptions_cultureInvariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECMA Script.
        /// </summary>
        public static string regexOptions_ecmaScript {
            get {
                return ResourceManager.GetString("regexOptions_ecmaScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit capture.
        /// </summary>
        public static string regexOptions_explicitCapture {
            get {
                return ResourceManager.GetString("regexOptions_explicitCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore case.
        /// </summary>
        public static string regexOptions_ignoreCase {
            get {
                return ResourceManager.GetString("regexOptions_ignoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore pattern whitespace.
        /// </summary>
        public static string regexOptions_ignorePatternWhitespace {
            get {
                return ResourceManager.GetString("regexOptions_ignorePatternWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiline.
        /// </summary>
        public static string regexOptions_multiline {
            get {
                return ResourceManager.GetString("regexOptions_multiline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-to-left.
        /// </summary>
        public static string regexOptions_rightToLeft {
            get {
                return ResourceManager.GetString("regexOptions_rightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singleline.
        /// </summary>
        public static string regexOptions_singleline {
            get {
                return ResourceManager.GetString("regexOptions_singleline", resourceCulture);
            }
        }
    }
}
